### PR TITLE
updated testing-server-behave based on restructrued code

### LINKED ISSUE #111: Write behaviour test scenario for testing server
**As a** developer
**I need** a behaviour test scenario for testing server
**So that** the sever is running 

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

### PR DESCRIPTION
**Pull request by lingy1028**
close #111

### CODE REVIEW

**Comment by meetparekh09** [comment]
When I enter following commands
* `vagrant up`
* `cd /vagrant`
* `behave`

Then, I get following results:
```
Failing scenarios:
  features/inventory.feature:6  The server is running

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 1 failed, 2 skipped, 0 undefined
Took 0m0.022s
```

Which suggests that our behaviour test cases are failing...

**Comment by lingy1028** [comment]
I used the command $python run.py & before $behave, and I got the feature
passed.

   - vagrant up
   - cd /vagrant
   -

   python run.py &
   - behave

[image: Screen Shot 2018-12-04 at 4.13.19 PM.png]

**Comment by lingy1028** [comment]
screen shot 2018-12-04 at 4 13 19 pm

**Comment by meetparekh09** [comment]
Oh Sorry for that, I completely missed to start the server.

**Pull request merged**
